services:
  private-ai-openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: private-ai-openwebui
    ports:
      - "${HOST_PORT}:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    volumes:
      - private-ai-data:/app/backend/data
    networks:
      - ai-network

networks:
  ai-network:
    external: true
volumes:
  private-ai-data:
