services:
  private-ai-n8n:
    image: n8nio/n8n:latest
    container_name: private-ai-n8n
    ports:
      - "${HOST_PORT}:5678"
    volumes:
      - private-ai-data:/home/node/.n8n
    networks:
      - ai-network

networks:
  ai-network:
    external: true
volumes:
  private-ai-data:
