services:
  private-ai-postgres:
    image: ankane/pgvector
    container_name: private-ai-postgres
    ports:
      - "${HOST_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - private-ai-data:/var/lib/postgresql/data
    networks:
      - ai-network

networks:
  ai-network:
    external: true
volumes:
  private-ai-data:
